Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
AllCops:
  Exclude:
    - db/**/*
    - Gemfile
    - tmp/**/*
    - bin/**/*
    - vendor/**/*
    - scripts/**/*
    - config/**/*
