version: '2'
services:
  db:
    image: postgres:9.3.5
    ports:
      - "5432:5432"
  web:
    build:
      context: .
    command: rails s -b 0.0.0.0
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - db:db
    #   - redis:redis
    mem_limit: 512m
    # extends:
    #   file: docker-compose-common.yml
    #   service: development_envs
    environment:
      PORT: 3000
