version: '2'
services:
  db:
    image: postgres:9.4.7
    ports:
      - "5432:5432"
  web:
    build:
      context: .
    command: bundle exec rake test
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - db:db
    mem_limit: 512m
    environment:
      PORT: 3000
      RACK_ENV: test
      RAILS_ENV: test
